import React from "react";
import Link from "next/link";
import Router from "next/router";
import socket from "./utils/socket";
import Head from "next/head";
import axios from "axios";
import userStore from "./store";

export default function Auth() {
  const [numberRoom, setNumberRoom] = React.useState("");
  const [nickname, setNickname] = React.useState("");

  const addUsers = userStore((state) => state.addUsers);
  const addUser = userStore((state) => state.addUser);
  //const resetMessages = userStore((state) => state.resetMessages);
  const resetUsers = userStore((state) => state.resetUsers);
  //const setMessages = userStore((state) => state.setMessages);

  const onEnter = async () => {
    //Обработка полей
    if (!numberRoom || !nickname) {
      return alert("Неверные данные");
    }
    //Добавление юзера в Zustand
    addUser({ nickname: nickname, room: numberRoom });
    //Инициализация сокета с подключением
    socket.emit("room:join", {
      numberRoom,
      nickname,
    });
    //Запрос на получение юзеров и сообщений в комнате
    resetUsers();
    try {
      const { data } = await axios.get(
        `http://localhost:4000/rooms/${numberRoom}`
      );
      addUsers(data.users);
      Router.push("/chat");
    } catch (error) {
      console.log(error);
    }
    //Переадресация на чат
  };

  return (
    <>
      <Head>
        <title>Hagenti.Chat - Вход</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <div className='container'>
          <div className='auth_form'>
            <section>
              <input
                value={numberRoom}
                onChange={(e) => setNumberRoom(e.target.value)}
                placeholder='Номер комнаты'
              />
              <input
                value={nickname}
                onChange={(e) => setNickname(e.target.value)}
                placeholder='Никнейм'
              />
              <button onClick={onEnter}>Войти</button>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
