import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "./components/header";
import { useInView } from "react-intersection-observer";
import Link from "next/link";

export default function Home() {
  const [ref, inView] = useInView({
    threshold: 0,
  });

  const [ref1, inView1] = useInView({
    threshold: 0,
  });

  return (
    <>
      <Head>
        <title>Hagenti.Chat</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <section className='sticky_container'>
          <div className='main_block '>
            <div className='container'>
              <div>
                <h1>Hagenti.Chat</h1>
                <h1>Этот чат просто имба</h1>
                <Link href='/auth'>
                  <button>Начать</button>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <div className='sticky_container'>
          <div
            ref={ref}
            className={inView ? "main_bot_block_2 black" : "main_bot_block_2 "}
          >
            <div className='container'>
              <section>
                <div>
                  <h2>О проекте</h2>
                </div>
                <div>
                  <div>
                    <div>
                      <h2>Краткое описание</h2>
                      <p>Простой, удобный и красивый чат 😎</p>
                    </div>
                    <div>
                      <h2>Стэк технологий</h2>
                      <p>
                        React.JS / Zubstand / Socket.IO / Node.JS / Express /
                        TypeScript / SCSS.
                      </p>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </main>
      <footer>
        <div></div>
      </footer>
    </>
  );
}
